server:
  port: 9093

spring:
  application:
    name: operations-service
  datasource:
    url: jdbc:postgresql://switchback.proxy.rlwy.net:16602/railway
    username: postgres
    password: tBEcFMqrsXUQjPqrzkkCjVRMPyOBVsWo
    driver-class-name: org.postgresql.Driver


external:
  services:
    credit-card:
      url: http://127.0.0.1:9000